schema_version = "1.0.0"

id = "squared_media_rig_ui"
version = "2.0.0"
name = "Squared Media Pro Rig V1"
tagline = "UI for controlling Squared Media's rigs in Blender"
maintainer = "Fxnarji <fxn-work@proton.me>"
type = "add-on"

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
files = "for loading rig configurations and Skins"